---
- hosts: k8s-cluster
  name: Powerup cluster nodes
  connection: local
  tasks:
    - name: Power up the host
      command: virsh start {{ host_name }}

    - name: Wait for host to come up
      wait_for_connection: delay=20
